// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
:projectid: docker
:page-layout: guide
:page-duration: 20 minutes
:page-description: Learn how to develop an application with Open Liberty and Docker.
:page-tags: ['Docker']
:page-related-guides: []
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Developing an application with Open Liberty and Docker

Learn how to develop an application with Open Liberty and Docker containers.

// =================================================================================================
// Introduction
// =================================================================================================

== What you'll learn

You will learn how to run and continuously develop a simple REST application with Open Liberty and Docker.

The REST application that you will run was written for you in advance and can be found in the
`app` directory. To learn more about this application and how to build it, read
https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service].

To containerize your application, first build it with Maven and add it to the servers of
your choice. Second, create a Docker image that contains an Open Liberty runtime. Third, run this image
and mount a single server directory or the directory that contains all of your servers to the container's
file system. Finally, run one of the mounted servers inside of a container.

=== What is Docker?

Docker is a tool that you can use to deploy and run applications with containers. You
can think of Docker like a virtual machine that runs various applications. However, unlike a typical virtual
machine, you can run these applications simultaneously on a single system and independent of
one another.

Learn more about Docker on the official Docker page: https://www.docker.com/what-docker

Learn how to install Docker on the official instructions page: https://docs.docker.com/engine/installation

=== What is a container?

A container is a lightweight, stand-alone package that contains a piece of software that is bundled together
with the entire environment that it needs to run. Containers are small compared to regular images and can
run on any environment where Docker is set up. Moreover, you can run multiple containers on a single
machine at the same time in isolation from each other.

Learn more about containers on the official Docker page: https://www.docker.com/what-container

=== Why use containers?

Consider a scenario where you need to deploy your application on another environment. Your application
works on your local machine, but when you try to run it on a different environment, it breaks. You do
some debugging and discover that you built your application with Python 3,
but this new environment has only Python 2.7 installed. Although this issue is generally easy to fix,
you don't want your application to be missing dozens of version-specific dependencies.
You can create a virtual machine specifically for testing your application, but VM images generally
take up a huge amount of space and are slow to run.

To solve the problem, you can containerize your application by
bundling it together with the entire environment that it needs to run. You can then run this container
on any machine that is running Docker regardless of how that machine's environment is set up. You can also run multiple
containers on a single machine in isolation from one another so that two containers that have different
versions of Python do not interfere with each other. Containers are quick to run compared to individual VMs,
and they take up only a fraction of the memory of a single image.

// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Creating the Dockerfile
// =================================================================================================

== Creating the Dockerfile

A Dockerfile is a collection of instructions to build a Docker image that you can then
run as a container. Every Dockerfile begins
with a parent or base image on top of which these instructions are run. For example, you can start
your image from scratch and execute commands that download Java, or you can start from
an image that already contains a Java installation.

Use the `openliberty/open-liberty:javaee7` image that contains the Open Liberty
runtime as the parent image.

Before you write your Dockerfile, familiarize yourself with the types of instructions that are compatible
with Dockerfiles. Use the following instructions to build a Dockerfile for this guide:

[cols="70, 100"]
|===
| *Command* | *Description*
| FROM <image> | This command initializes a new build stage and indicates the parent image from which your image
is built, or you can use `FROM scratch` to indicate that your image is a base image.
| RUN <commands> | This command executes the commands in a new layer on top of the current image.
| CMD ["executable", "param1", "param2"] | This command defines the command to be executed when the image runs.
| ENTRYPOINT ["executable", "param1", "param2"] | This command works similarly to the `CMD` command, but unlike
`CMD`, only the `--entrypoint` flag can override `ENTRYPOINT`.
|===

For a more extensive and detailed list, see the official https://docs.docker.com/engine/reference/builder[Docker documentation].

=== Writing your Dockerfile

To begin, specify `openliberty/open-liberty:javaee7` as the parent image. This image contains the Open Liberty runtime.

Create a regular `start/Dockerfile` file:

[source, indent=0]
----
include::finish/Dockerfile[tags=from]
----

By default, the Open Liberty runtime is downloaded to the `/opt/ol/wlp` directory.

Next, create a symlink between the `/opt/ol/wlp/usr/servers` directory and the `/servers` directory.
This symlink makes mounting your servers easier because you won't have to type long path names:

[source, indent=0]
----
include::finish/Dockerfile[tags=link]
----

Although you have only one `RUN` instruction in your Dockerfile, you can tie multiple
`RUN` instructions together to minimize the number of layers in your image and reduce build time. While
maintaining readability, try to minimize the number of layers in your image, as shown in the following example:

[role="no_copy"]
----
RUN mkdir dir1 \
    && mv dir1 dir2 \
    && cp dir2 dir3
----

Finally, use the `ENTRYPOINT` instruction to run the `server` script and use the `CMD` instruction to
specify which server to start. Because a user can override `CMD` calls, you can override the
`defaultServer` name with another server name when running the container:

[source, indent=0]
----
include::finish/Dockerfile[tags=default-start]
----

Your Dockerfile is complete. Use it to build your image.

=== Optional: Writing a `.dockerignore` file

When Docker runs a build, it sends all of the files and directories in the same directory as the
Dockerfile to its build context. With all of the files and directories in the build context, you can
use them in instructions like `ADD` and `COPY`. To increase build performance, exclude all of the files
and directories that aren't necessary for building your image. Add these files and directories to a `.dockerignore` file.

A `.dockerignore` file already exists in the `start` directory. This file includes the
`app` directory and some system files. This directory and files are excluded from the build context
when you execute a Docker build. Add any other files or directories that you want to exclude.

// =================================================================================================
// Building the image
// =================================================================================================

== Building the image

To build your image, make sure that your Docker daemon is running and execute the Docker `build` command
from the command line. If you execute your build from the same directory as your Dockerfile, you can
use the `.` notation. Otherwise, use the `-f` flag to point to your Dockerfile:

```
docker build -t ol-runtime .
```

Use the `-t` flag to give the image an optional name. In this case, `ol-runtime` is the name of your image.

The first build usually takes much longer to complete than subsequent builds because Docker needs to
download all dependencies that your image requires, including the parent image.

If your build runs successfully, an output appears that is similar to the following example:

[role="no_copy"]
----
Sending build context to Docker daemon  3.072kB
Step 1/4 : FROM openliberty/open-liberty:javaee7
javaee7: Pulling from openliberty/open-liberty
660c48dd555d: Pull complete
4c7380416e78: Pull complete
421e436b5f80: Pull complete
e4ce6c3651b3: Pull complete
be588e74bd34: Pull complete
6da4611cbdb3: Pull complete
3cbd5728a38e: Pull complete
38f12bc85354: Pull complete
540c270bda6a: Pull complete
bbd56d34f762: Pull complete
8f181e95aa97: Pull complete
4c14e095e68e: Pull complete
bed46b62b8c3: Pull complete
Digest: sha256:d6793b7865d86ad43e5cc7c02089f7eefd2b1af3e312bc453e4779f4f24c28a6
Status: Downloaded newer image for openliberty/open-liberty:javaee7
 ---> d71303f77e8d
Step 2/4 : RUN ln -s /opt/ol/wlp/usr/servers /servers
 ---> Running in 191078d2ce16
 ---> dfef8073fe42
Removing intermediate container 191078d2ce16
Step 3/4 : ENTRYPOINT /opt/ol/wlp/bin/server run
 ---> Running in 38e48bae6dd7
 ---> 1015cbcdcf37
Removing intermediate container 38e48bae6dd7
Step 4/4 : CMD defaultServer
 ---> Running in 3fea454efdcd
 ---> ee99661593eb
Removing intermediate container 3fea454efdcd
Successfully built ee99661593eb
Successfully tagged ol-runtime:latest
----

Each step of the build has a unique ID, which is an ID of an intermediate image. For example, step 2
has the ID `dfef8073fe42`, and step 4 has the ID `ee99661593eb`, which is also the ID of the final image.
During the first build of your image, Docker caches every new layer as a separate image and reuses them
for future builds for steps that didn't change. For example, if you run the build again, Docker reuses
the images that it cached for steps 2 - 4. However, you can tweak the `CMD` instruction and change the
`defaultServer` server to the `testServer` server, and then Docker reuses the intermediate images for only steps 2 - 3.

You can pass in the `--no-cache=true` command into the build to disable the caching of intermediate images:

```
docker build -t ol-runtime --no-cache=true .
```

Learn more about the build process on the official Docker page: https://docs.docker.com/engine/reference/commandline/image_build

// =================================================================================================
// Building your application
// =================================================================================================

== Building your application

To build your application, run the Maven `clean` and `install` goals from the `app` directory:

[role="no_copy"]
----
cd app
mvn clean install
----

Your `pom.xml` file is already configured to add your REST application to the `defaultServer` server,
but you can tweak this configuration or add your own for another server:

[source, xml, indent=0]
----
<!-- Install the app into the apps/ directory of defaultServer -->
<execution>
    <id>install-app</id>
    <phase>package</phase>
    <goals>
        <goal>install-apps</goal>
    </goals>
    <configuration>
        <appsDirectory>apps</appsDirectory>
        <stripVersion>true</stripVersion>
        <installAppPackages>project</installAppPackages>
    </configuration>
</execution>
----

The `install-apps` goal copies the application into the specified directory of the specified server.
In this case, the goal copies the `rest.war` file into the `apps` directory of the `defaultServer` server.

Learn more about this goal on the official https://github.com/WASdev/ci.maven/blob/master/docs/install-apps.md[Maven Liberty plug-in repository].

// =================================================================================================
// Containerize your application
// =================================================================================================

== Containerize your application

Now that your image is built, execute the Docker `run` command from the command line to run it:

```
docker run -d --name rest-app -p 9080:9080 -p 9443:9443 -v <absolute path to guide>/start/app/target/liberty/wlp/usr/servers:/servers ol-runtime
```

Alternatively, you can also execute the `run` command to mount a single server instead of the whole `servers` directory:

```
docker run -d --name rest-app -p 9080:9080 -p 9443:9443 -v <absolute path to guide>/start/app/target/liberty/wlp/usr/servers/defaultServer:/servers/defaultServer ol-runtime
```

The following table displays the functions of the flags:

[cols="15, 100"]
|===
| *Flag* | *Description*
| -d | This flag tells Docker to run the container in the background. Without this flag, Docker runs
the container in the foreground.
| --name | This flag gives the container a name.
| -p | This flag maps the container ports to the host ports.
| -v | This flag mounts a directory or file to the file system of the container.
|===

You can pass in an optional server name at the end of the `run` command to override the `defaultServer`
server in the `CMD` instruction. For example, if your `servers` directory also contains a server called
`testServer`, then it can be started as shown in the following example:

```
docker run -d --name rest-app -p 9080:9080 -p 9443:9443 -v <absolute path to guide>/start/app/target/liberty/wlp/usr/servers:/servers ol-runtime testServer
```

Learn more about running containers on the official Docker page: https://docs.docker.com/engine/reference/run

// =================================================================================================
// Testing the container
// =================================================================================================

== Testing the container

Before you access your application from the browser, run the `docker ps` command from the
command line to make sure that your container is running and didn't crash. The following example output
is truncated for conciseness:

[role="no_copy"]
----
$ docker ps
CONTAINER ID        IMAGE               CREATED             STATUS              NAMES
2720cea71700        ol-runtime          2 seconds ago       Up 1 second         rest-app
----

To view a full list of all available containers, run the `docker ps -a` command from the command line.

If your container is running without problems, point your browser to `http://localhost:9080/LibertyProject/System/properties`,
where you can see a JSON file that contains the system properties of the JVM in your container.

Edit the `app/src/main/java/io/openliberty/guides/rest/PropertiesResource.java` class and change the `@Path`
annotation to `"properties-new"`. These edits change the endpoint of your application from `/properties` to `/properties-new`:

[source, Java, indent=0]
----
@Path("properties-new")
public class PropertiesResource {
  ...
}
----

To see these changes reflected in the container, run the `mvn package` command from the command line to
rebuild your application and point your browser to `http://localhost:9080/LibertyProject/System/properties-new`.
You see the same JSON file that you saw previously.

To stop your container, run the `docker stop rest-app` command from the command line.

If a problem occurs and your container exits prematurely, the container does not appear in the container
list that the `docker ps` command displays. Instead, your container appears with an `Exited`
status when you run the `docker ps -a` command. Run the `docker rm rest-app` command to remove your container.
Next, check your Dockerfile for potential problems. You can also run the container in the foreground to
see whether any error messages are displayed.

== Great work! You're done!

You containerized a simple REST application. You can now continuously deliver changes to the application,
and they will reflect automatically when the application rebuilds.


include::{common-includes}/finish.adoc[]
