// Copyright (c) 2017, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
:projectid: docker
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-description: Learn how to use Docker containers for iterative development. 
:page-releasedate: 2017-12-27
:page-tags: ['Docker']
:page-related-guides: ['rest-intro']
:page-guide-category: basic
:page-essential: true
:page-essential-order: 4
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:guide-author: Open Liberty
= Using Docker containers to develop microservices

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to use Docker containers for iterative development.

:linux: LINUX
:win: WINDOWS
:mac: MAC

// =================================================================================================
// Introduction
// =================================================================================================

== What you'll learn

You will learn how to set up, run, and iteratively develop a simple REST application in a container with Open Liberty and Docker.

The implementation of the REST application can be found in the
`start/src` directory. To learn more about this application and how to build it, read
https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service^].

To iteratively develop your application in a container, first build it with Maven and add it to the servers of
your choice. Second, create a Docker image that contains an Open Liberty runtime. Third, run this image
and mount a single server directory or the directory that contains all of your servers to the container's
file system. Finally, run one of the mounted servers inside of a container.

=== What is Docker?

Docker is a tool that you can use to deploy and run applications with containers. You
can think of Docker like a virtual machine that runs various applications. However, unlike a typical virtual
machine, you can run these applications simultaneously on a single system and independent of
one another.

Learn more about Docker on the https://www.docker.com/what-docker[official Docker page^].

Learn how to install Docker on the https://docs.docker.com/engine/installation[official instructions page^].

=== What is a container?

A container is a lightweight, stand-alone package that contains a piece of software that is bundled together
with the entire environment that it needs to run. Containers are small compared to regular images and can
run on any environment where Docker is set up. Moreover, you can run multiple containers on a single
machine at the same time in isolation from each other.

Learn more about containers on the https://www.docker.com/what-container[official Docker page^].

=== Why use containers?

Consider a scenario where you need to deploy your application on another environment. Your application
works on your local machine, but when you try to run it on a different environment, it breaks. You do
some debugging and discover that you built your application with Python 3,
but this new environment has only Python 2.7 installed. Although this issue is generally easy to fix,
you don't want your application to be missing dozens of version-specific dependencies.
You can create a virtual machine specifically for testing your application, but VM images generally
take up a huge amount of space and are slow to run.

To solve the problem, you can containerize your application by
bundling it together with the entire environment that it needs to run. You can then run this container
on any machine that is running Docker regardless of how that machine's environment is set up. You can also run multiple
containers on a single machine in isolation from one another so that two containers that have different
versions of Python do not interfere with each other. Containers are quick to run compared to individual VMs,
and they take up only a fraction of the memory of a single image.

// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Building your application
// =================================================================================================

== Building your application

Before you begin, build your application. To do this, navigate to the `start` directory and run the Maven
`install` goal:

[role='command']
```
mvn install
```

Your [hotspot]`pom.xml` file is already configured to add your REST application to the `defaultServer`. But you can tweak this configuration or add your own for another server by updating the [hotspot=185-196]`<execution/>` element.

The [hotspot=189]`install-apps` goal copies the application into the specified directory of the specified server.
In this case, the goal copies the `rest.war` file into the [hotspot=192]`apps` directory of the `defaultServer` server.

Learn more about this goal on the official https://github.com/WASdev/ci.maven/blob/2.x/docs/install-apps.md[Maven Liberty plug-in repository^].

pom.xml
[source, xml, linenums, role="code_column"]
----
include::finish/pom.xml[tags=**]
----

// =================================================================================================
// Creating the Dockerfile
// =================================================================================================

== Creating the Dockerfile

A Dockerfile is a collection of instructions for building a Docker image that can then be run as a
container. Every Dockerfile begins with a parent or base image on top of which various commands
are run. For example, you can start your image from scratch and execute commands that download and
install Java, or you can start from an image that already contains a Java installation.

Navigate to the `start` directory to begin.

[role="code_command hotspot",subs="quotes"]
----
#Create the `Dockerfile`.#
`Dockerfile`
----

The [hotspot=2 file=0]`FROM` instruction initializes a new build stage and indicates the parent image from which your
image is built. If you don't need a parent image, then use `FROM scratch`, which makes your image a
base image. 

In this case, you're using the `openliberty/open-liberty:javaee8` image as your parent
image, which comes with the latest Open Liberty runtime.


The [hotspot=6 file=0]`RUN` instruction executes various shell commands in a new layer on top of the current image.
In this case, you create a symlink between the `/opt/ol/wlp/usr/servers` directory and the `/servers`
directory. This way, you can mount your servers more easily because you don't need to use long path names.
Note that since the Open Liberty Docker image runs by default with user `1001` (which is a non-root user),
you must temporarily switch to the `root` user to create the symlink. This is done by using 
the [hotspot=4 hotspot=7 file=0]`USER` instruction. 

The [hotspot=10 file=0]`ENTRYPOINT` and [hotspot=11]`CMD` instructions define a default command that executes when the image runs as
a container. These two instructions function the same way, except that the [hotspot=11 file=0]`CMD` instruction is overridden
with any arguments that are passed at the end of the `docker run` command. In contrast, the
[hotspot=10 file=0]`ENTRYPOINT` instruction requires the `--entrypoint` flag to be overridden. In this case, you use
the [hotspot=10 file=0]`ENTRYPOINT` instruction to start an Open Liberty server and the [hotspot=11 file=0]`CMD` instruction to indicate
which server to start. Because the [hotspot=11 file=0]`CMD` instruction is easily overridden, starting any server is convenient.

For a complete list of available instructions, see the https://docs.docker.com/engine/reference/builder[Docker documentation^].

Dockerfile
[source, text, linenums, role="code_column"]
----
include::finish/Dockerfile[tags=**]
----

=== Optional: Writing a .dockerignore file

When Docker runs a build, it sends all of the files and directories that are located in the same directory
as the Dockerfile to its build context, making them available for use in instructions like `ADD` and `COPY`.
To make image building faster, add all files and directories that aren't necessary for building your
image to a `.dockerignore` file. This excludes them from the build context.

A [hotspot file=0]`.dockerignore` file is available to you in the `start` directory. This file includes the [hotspot=2 file=0]`src`
directory, the [hotspot file=1]`pom.xml` file, and some system files. Feel free to add anything else that you want to exclude.

`.dockerignore`
[source, text, linenums, role="code_column"]
----
include::finish/.dockerignore[tags=**]
----

pom.xml
[source, xml, linenums, role="code_column"]
----
include::finish/pom.xml[tags=**]
----
// =================================================================================================
// Building the image
// =================================================================================================

== Building the image

To build your image, make sure that your Docker daemon is running and execute the Docker `build` command
from the command line. If you execute your build from the same directory as your Dockerfile, you can
use the period character (`.`) notation to specify the location for the build context. Otherwise, use
the `-f` flag to point to your Dockerfile:
[role='command']
```
docker build -t ol-runtime .
```

Use the `-t` flag to give the image an optional name. In this case, `ol-runtime` is the name of your image.

The first build usually takes much longer to complete than subsequent builds because Docker needs to
download all dependencies that your image requires, including the parent image.

If your build runs successfully, you'll see an output similar to the following:

[role="no_copy"]
----
Sending build context to Docker daemon  148.9MB
Step 1/4 : FROM open-liberty
latest: Pulling from library/open-liberty
7b8b6451c85f: Pull complete 
ab4d1096d9ba: Pull complete 
e6797d1788ac: Pull complete 
e25c5c290bde: Pull complete 
27b2fbbc72b1: Pull complete 
aa35dfd74487: Pull complete 
1ade56d64661: Pull complete 
3493ef172f60: Pull complete 
cd6dff6d245d: Pull complete 
82450af30afc: Pull complete 
Digest: sha256:b7576e4278030537765d4185c4641ee2769194226263f979109ed4fa0e1aa4e4
Status: Downloaded newer image for open-liberty:latest
 ---> 45d4b67ace5b
Step 2/4 : RUN ln -s /opt/ol/wlp/usr/servers /servers
 ---> Running in cbeb275770ab
Removing intermediate container cbeb275770ab
 ---> 937183f8460b
Step 3/4 : ENTRYPOINT ["/opt/ol/wlp/bin/server", "run"]
 ---> Running in 856a4bdec82b
Removing intermediate container 856a4bdec82b
 ---> 6cf732381877
Step 4/4 : CMD ["defaultServer"]
 ---> Running in 1a543a9e37d8
Removing intermediate container 1a543a9e37d8
 ---> 8fdcad065d25
Successfully built 8fdcad065d25
Successfully tagged ol-runtime:latest
----

Each step of the build has a unique ID, which represents the ID of an intermediate image. For example, step 2
has the ID `937183f8460b`, and step 4 has the ID `8fdcad065d25`, which is also the ID of the final image.
During the first build of your image, Docker caches every new layer as a separate image and reuses them
for future builds for layers that didn't change. For example, if you run the build again, Docker reuses
the images that it cached for steps 2 - 4. However, if you make a change in your Dockerfile, Docker would
need to rebuild the subsequent layer since this layer also changed.

However, you can also completely disable the caching of intermediate layers by running the build with the
`--no-cache=true` flag:

[role='command']
```
docker build -t ol-runtime --no-cache=true .
```

Learn more about the image build process on the https://docs.docker.com/engine/reference/commandline/image_build[Docker documentation^].


// =================================================================================================
// Running your application in Docker container
// =================================================================================================

== Running your application in Docker container

Now that your image is built, execute the Docker `run` command with the absolute path to this guide:

include::{common-includes}/os-tabs.adoc[]

[.tab_content.windows_section.mac_section]
--
[role='command']
```
docker run -d --name rest-app -p 9080:9080 -p 9443:9443 -v <absolute path to guide>/start/target/liberty/wlp/usr/servers:/servers ol-runtime
```
--

[.tab_content.linux_section]
--
Use the `-u` flag to override the default user within the container to match the user 
id on your host machine. This is to ensure the default user has correct permissions to the 
server directory. 

[role='command']
```
docker run -d --name rest-app -p 9080:9080 -p 9443:9443 -v <absolute path to guide>/start/target/liberty/wlp/usr/servers:/servers -u `id -u` ol-runtime
```
--

Alternatively, you can also execute the `run` command to mount a single server instead of the whole `servers` directory:
[role='command']

include::{common-includes}/os-tabs.adoc[]

[.tab_content.windows_section.mac_section]
--
[role='command']
```
docker run -d --name rest-app -p 9080:9080 -p 9443:9443 -v <absolute path to guide>/start/target/liberty/wlp/usr/servers/defaultServer:/servers/defaultServer ol-runtime
```
--

[.tab_content.linux_section]
--
[role='command']
```
docker run -d --name rest-app -p 9080:9080 -p 9443:9443 -v <absolute path to guide>/start/target/liberty/wlp/usr/servers/defaultServer:/servers/defaultServer -u `id -u` ol-runtime
```
--

Let's break down the flags:

[cols="15, 100", options="header"]
|===
| *Flag* | *Description*
| -d | This flag tells Docker to run the container in the background. Without this flag, Docker runs
the container in the foreground.
| --name | This flag specifies a name for the container.
| -p | This flag maps the container ports to the host ports.
| -v | This flag mounts a directory or file to the file system of the container.
|===

You can pass in an optional server name at the end of the `run` command to override the `defaultServer`
server in the `CMD` instruction. For example, if your `servers` directory also contains a server called
`testServer`, then it can be started as shown in the following example:

[role='no_copy']
```
docker run -d --name rest-app -p 9080:9080 -p 9443:9443 -v <absolute path to guide>/start/target/liberty/wlp/usr/servers:/servers ol-runtime testServer
```

Learn more about running containers on the https://docs.docker.com/engine/reference/run[official Docker page^]

// =================================================================================================
// Testing the container
// =================================================================================================

== Testing the container

Before you access your application from the browser, run the `docker ps` command from the
command line to make sure that your container is running and didn't crash:

[role="no_copy"]
----
$ docker ps
CONTAINER ID        IMAGE               CREATED             STATUS              NAMES
2720cea71700        ol-runtime          2 seconds ago       Up 1 second         rest-app
----

To view a full list of all available containers, run the `docker ps -a` command from the command line.

If your container is running without problems, point your browser to http://localhost:9080/LibertyProject/System/properties[http://localhost:9080/LibertyProject/System/properties^],
where you can see a JSON file that contains the system properties of the JVM in your container.
[role="code_command hotspot", subs="quotes"]
----
#Update the `PropertiesResource` class.#
`src/main/java/io/openliberty/guides/rest/PropertiesResource.java`
----

[role="edit_command_text"]
Change the endpoint of your application from `properties` to `properties-new` by changing the [hotspot=18]`@Path`
annotation to `"properties-new"`.


To see these changes reflected in the container, run the following command from the command line to
rebuild your application and point your browser to http://localhost:9080/LibertyProject/System/properties-new[http://localhost:9080/LibertyProject/System/properties-new^].
[role='command']
```
mvn package
```
You see the same JSON file that you saw previously.

To stop your container, run the following command from the command line.
[role='command']
```
docker stop rest-app
```

If a problem occurs and your container exits prematurely, the container won't appear in the container
list that the `docker ps` command displays. Instead, your container appears with an `Exited`
status when you run the `docker ps -a` command. Run the `docker logs rest-app` command to view the
container logs for any potential problems and double-check that your Dockerfile is correct. When you
find the cause of the issue, remove the faulty container with the `docker rm rest-app` command, rebuild
your image, and start the container again.

PropertiesResource.java
[source, Java, linenums, role="code_column"]
----
include::finish/src/main/java/io/openliberty/guides/rest/PropertiesResource.java[tags=**;!comment]
----

== Great work! You're done!

You have learned how to set up, run, iteractively develop a simple REST application in a container with
Open Liberty and Docker. Whenever you make changes to your application code, they will now reflect
automatically on the Open Liberty server running in a container when the application rebuilds.



include::{common-includes}/attribution.adoc[subs="attributes"]
